### ISSUE TITLE
삭제후 미리보기 화면에서 보여지는 문제

### ISSUE THREAD

**Issue by simuelunbo** [Fastcampus-Android-Lecture-Project-2021/aop-part5-chapter03#1]
해당 프로젝트에서 사진찍고 난후 previewImageView 사진 리스트에서 사진을 삭제하고 사진 찍는 화면으로 돌아가면 previewImageView에 이미지가 남아 있는 문제가 있습니다. 
어떻게 해야 이부분을 해결 할수 있을까요?

**Comment by SODA1127** [comment]
@simuelunbo 확인해주셔서 감사합니다. 해당 이슈는 이 [커밋](https://github.com/Fastcampus-Android-Lecture-Project-2021/aop-part5-chapter03/commit/2b2b9574f942de62f0cc6a62c0b6189672d30e11)에서 수정되었습니다.

**Comment by simuelunbo** [comment]
답변 감사합니다 한가지 더 문제가 있는데요 2개 이상 찍은 사진 리스트들을 모두 삭제를 진행해도 해당 파일에 들어가면 일부 사진들이 삭제가 되지 않는 문제가 있습니다.

**Comment by SODA1127** [comment]
@simuelunbo 그부분도 마찬가지로 수정되었습니다. 568d2ae

**Comment by simuelunbo** [comment]
감사합니다
